"""Build EXPERIMENTS.md from every run in data/checkpoints/.

For each run it reads run_config.json, the per-stage history.csv files and the stage 2
val_preds.csv (dev probabilities at the best epoch), and reports APTOS dev metrics with
bootstrap 95% confidence intervals. Run it after each training run:

    python summarize.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score, roc_auc_score

CKPT = Path("data/checkpoints")
OUT = Path("EXPERIMENTS.md")
BASELINE = "iter1"
N_BOOT = 2000
GRADES = ["No DR", "Mild", "Moderate", "Severe", "Proliferative"]


def grades_and_referable(preds):
    """Predicted grade and referable-DR score, as training computes them.

    Classifiers: most likely grade and P(grade >= 2). Regression (`score` column): the score
    rounded to the nearest grade, and the score itself.
    """
    if "score" in preds:
        s = preds["score"].to_numpy()
        return np.digitize(s, [0.5, 1.5, 2.5, 3.5]), s
    p = preds[[f"p{c}" for c in range(5)]].to_numpy()
    return p.argmax(1), p[:, 2:].sum(1)


def bootstrap_ci(preds, seed=0):
    """95% percentile intervals for QWK and referable-DR AUC, resampling dev images."""
    y = preds["level"].to_numpy()
    pred, ref = grades_and_referable(preds)
    rng = np.random.default_rng(seed)
    qwks, aucs = [], []
    for _ in range(N_BOOT):
        i = rng.integers(0, len(y), len(y))
        qwks.append(cohen_kappa_score(y[i], pred[i], weights="quadratic"))
        if 0 < (y[i] >= 2).sum() < len(i):
            aucs.append(roc_auc_score(y[i] >= 2, ref[i]))
    return np.percentile(qwks, [2.5, 97.5]), np.percentile(aucs, [2.5, 97.5])


def paired_delta_ci(preds, base_preds, seed=0):
    """95% CI for (run QWK - baseline QWK), resampling the same dev images for both runs."""
    assert (preds["path"].to_numpy() == base_preds["path"].to_numpy()).all(), "dev order differs"
    y = preds["level"].to_numpy()
    a, b = grades_and_referable(preds)[0], grades_and_referable(base_preds)[0]
    rng = np.random.default_rng(seed)
    deltas = []
    for _ in range(N_BOOT):
        i = rng.integers(0, len(y), len(y))
        deltas.append(cohen_kappa_score(y[i], a[i], weights="quadratic")
                      - cohen_kappa_score(y[i], b[i], weights="quadratic"))
    return np.percentile(deltas, [2.5, 97.5])


def best_row(history_csv):
    h = pd.read_csv(history_csv)
    return h.loc[h["qwk"].idxmax()]          # first epoch with the best QWK, as training picks it


def summarize(run_dir):
    cfg = json.loads((run_dir / "run_config.json").read_text())
    s2 = run_dir / "stage2_aptos"
    if not (s2 / "history.csv").exists():
        return None
    b2 = best_row(s2 / "history.csv")
    row = {"run": cfg["RUN"], "desc": cfg.get("DESC", ""), "cfg": cfg,
           "dev_qwk": b2["qwk"], "dev_auc": b2["referable_auc"], "dev_loss": b2["loss"],
           "s2_epoch": int(b2["epoch"]) + 1, "s2_epochs_run": len(pd.read_csv(s2 / "history.csv")),
           "recalls": [b2[f"recall_{c}"] for c in range(5)],
           "refit": (run_dir / "model_stage2_refit.pt").exists()}
    if (s2 / "val_preds.csv").exists():
        row["preds"] = pd.read_csv(s2 / "val_preds.csv")
        row["qwk_ci"], row["auc_ci"] = bootstrap_ci(row["preds"])
    s1 = run_dir / "stage1_eyepacs" / "history.csv"
    if cfg.get("STAGE1_CKPT"):
        row["stage1"] = f"reused `{Path(cfg['STAGE1_CKPT']).parent.parent.name}`"
    elif s1.exists():
        b1 = best_row(s1)
        row["stage1"] = f"QWK {b1['qwk']:.3f}, AUC {b1['referable_auc']:.3f} (epoch {int(b1['epoch']) + 1})"
    return row


def fmt_ci(ci):
    return f" ({ci[0]:.3f}–{ci[1]:.3f})" if ci is not None else ""


def main():
    runs = [r for d in sorted(CKPT.iterdir())
            if (d / "run_config.json").exists() and d.name != "smoke" and (r := summarize(d))]
    runs.sort(key=lambda r: r["cfg"].get("started", ""))
    base = next((r for r in runs if r["run"] == BASELINE), None)

    lines = [
        "# Experiments",
        "",
        "Diabetic retinopathy grading: ResNet50 pretrained on EyePACS (stage 1), fine-tuned on APTOS 2019 (stage 2).",
        "All numbers are on the **APTOS dev split** (366 images), at the epoch with the best dev QWK. "
        "Dev is also used to pick that epoch, so these scores are slightly optimistic; "
        "APTOS test and Messidor-2 are held out until the final evaluation.",
        "",
        f"Brackets are bootstrap 95% confidence intervals ({N_BOOT} resamples of dev images). "
        "The Δ column's interval is **paired**: both runs are scored on the same resampled images, "
        "so it's much tighter than comparing the two runs' own intervals. "
        "A change is a real improvement only if its Δ interval is above 0.",
        "",
        "_Generated by `summarize.py` from `data/checkpoints/*/`._",
        "",
        "## Results",
        "",
        "| Run | Change | Dev QWK (95% CI) | Δ QWK vs baseline | Referable AUC (95% CI) | Recall 0 / 1 / 2 / 3 / 4 | Best epoch |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in runs:
        delta = "—"
        if base and r is not base:
            delta = f"{r['dev_qwk'] - base['dev_qwk']:+.3f}"
            if "preds" in r and "preds" in base:
                delta += fmt_ci(paired_delta_ci(r["preds"], base["preds"])).replace("–", " to ")
        recalls = " / ".join(f"{x:.2f}" for x in r["recalls"])
        lines.append(f"| `{r['run']}` | {r['desc']} | {r['dev_qwk']:.3f}{fmt_ci(r.get('qwk_ci'))} | {delta} "
                     f"| {r['dev_auc']:.3f}{fmt_ci(r.get('auc_ci'))} | {recalls} "
                     f"| {r['s2_epoch']} of {r['s2_epochs_run']} |")

    lines += ["", "## Run details", ""]
    for r in runs:
        c = r["cfg"]
        lines += [
            f"### `{r['run']}`",
            "",
            f"- **Change:** {r['desc'] or '—'}",
            f"- **Command:** `{c['command']}`",
            f"- **Started:** {c.get('started', '?')}",
            f"- **Settings:** {'regression (weighted MSE, rounded)' if c.get('REGRESSION') else 'classification'}, soft-label eps {c['SOFT_EPS']}, mixup α {c.get('MIXUP_ALPHA', 0)}, kappa-loss weight {c.get('KAPPA_WEIGHT', 0)}, {c['IMG_SIZE']} px, batch {c['BATCH_SIZE']}, "
            f"LR {c['LR_BACKBONE']:g} backbone / {c['LR_HEAD']:g} head (stage 2 ÷{c['STAGE2_LR_DIV']}), "
            f"cosine over {c['MAX_EPOCHS']} epochs, patience {c['PATIENCE']}, seed {c['SEED']}",
            f"- **Stage 1 (EyePACS holdout):** {r.get('stage1', '—')}",
            f"- **Stage 2 (APTOS dev):** QWK {r['dev_qwk']:.4f}, referable AUC {r['dev_auc']:.4f}, "
            f"val loss {r['dev_loss']:.4f}, best epoch {r['s2_epoch']} of {r['s2_epochs_run']}",
            f"- **Refit on train + dev:** {'yes (`model_stage2_refit.pt`)' if r['refit'] else 'no'}",
            "",
        ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(runs)} runs)")


if __name__ == "__main__":
    main()
